type AutoGenerated struct {
	First  First  `json:"first"`
	Second Second `json:"second"`
}
type Type struct {
	Long  string `json:"long"`
	Short string `json:"short"`
}
type First struct {
	Type Type `json:"type"`
	ID   int  `json:"id"`
}
type SecondType struct {
	Long string `json:"long"`
}
type Second struct {
	ID         int        `json:"id"`
	SecondType SecondType `json:"type"`
}
